# Setup

## Quarto {#sec-setup-quarto}

Add the files `PanRocq.theme` and `PanRocq.xml` to the root folder of your Quarto project. Then add the following `syntax-definitions` and `highlight-style` fields to the `_quarto.yml` file.

```yml
format:
  html:
    theme: cosmo
    syntax-definitions:
      - ./PanRocq.xml
    highlight-style: ./PanRocq.theme
  pdf:
    documentclass: scrreprt
    syntax-definitions:
      - ./PanRocq.xml
    highlight-style: ./PanRocq.theme
```

Any Quarto code block starting with a `rocq` fence will then be highlighted. See @sec-usage-quarto for an example. PanRocq is intended as a highlighting tool in light mode, where it matches standard Rocq highlighting rules. However, we have also included a version for Quarto's dark mode (see `PanRocq-dark.theme`), which can be configured as follows.

```yml
format:
  html:
    theme:
      light: cosmo
      dark: solar
    css: styles.css
    syntax-definitions:
      - ./PanRocq.xml
    highlight-style:
      light: ./PanRocq.theme
      dark: ./PanRocq-dark.theme
```

It renders reasonably well with the [Quarto themes](https://quarto.org/docs/output-formats/html-themes.html) `darkly`, `slate`, `solar` and `superhero`, but in that case we recommend importing the `styles.css` file that we provide if you want to use a scroll bar to deal with code block overflows.

## Typst {#sec-setup-typst}

Add the files `Rocq.sublime-syntax` and `Rocq.tmTheme` to your Typst directory. Then add the following to your `.typ` file.

```typst
#set raw(syntaxes: "Rocq.sublime-syntax", lang: "rocq", theme: "Rocq.tmTheme")
```

Any Typst code block starting with a `rocq` fence will then be highlighted. See @sec-usage-typst for an example.

## Pandoc {#sec-setup-pandoc}

Add the file `PanRocq.xml` to your working directory. See @sec-usage-pandoc for an example.
